project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - mp02.qmd
    - mp03.qmd
    - mp04.qmd

website:
  title: "Shubh Goyal | Data Analyst"
  navbar:
    title: "Shubh Goyal"
    left:
      - href: index.html
        text: Home
      - href: mp02.html
        text: Transit Analysis
      - href: mp03.html
        text: Spotify Playlist Analysis
      - href: mp04.html
        text: US Election Analysis

format:
  html:
    theme: cosmo
    toc: true
