project:
  type: website
  output-dir: docs

website:
  title: "Shubh Goyal | Data Analyst"
  navbar:
    title: "Shubh Goyal"
    left:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: Payroll Analysis
      - href: mp02.qmd
        text: Transit Analysis
      - href: mp03.qmd
        text: Spotify Playlist Analysis
      - href: mp04.qmd
        text: US Election Analysis

      

format:
  html:
    toc: true
